---
server:
  ip: "{{ lookup('env', 'IP') }}"
  maxconnection: "{{ lookup('env', 'MAXCONNECTION') }}"
  exectype: "{{ lookup('env', 'EXECTYPE') }}"
port:
  one: "{{ lookup('env', 'PORT1') }}"
  two: "{{ lookup('env', 'PORT2') }}"
  three: "{{ lookup('env', 'PORT3') }}"
  four: "{{ lookup('env', 'PORT4') }}"
  five: "{{ lookup('env', 'PORT5') }}"
  six: "{{ lookup('env', 'PORT6') }}"
  seven: "{{ lookup('env', 'PORT7') }}"
type:
  rtmp: "{{ lookup('env', 'RTMP') }}"
  hls: "{{ lookup('env', 'HLS') }}"
  dash: "{{ lookup('env', 'DASH') }}"
  rtmp2rtc: "{{ lookup('env', 'RTMP2RTC') }}"
  rtc: "{{ lookup('env', 'RTC') }}"
  hlsorigin: "{{ lookup('env', 'HLSORIGIN') }}"
  hlsedge: "{{ lookup('env', 'HLSEDGE') }}"
  rtc2rtmp: "{{ lookup('env', 'RTC2RTMP') }}"
  edge: "{{ lookup('env', 'EDGE') }}"